# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# trigger:
# - pull_request
pr:
  branches:
    include:
    - 'develop'
# parameters:
# - name: Branch
#   displayName: Branch to Deploy
#   type: string
#   default: feature
#   values:
#     - feature
#     - Develop
#     - main
variables:
  branchSource: "$(Build.SourceBranch)"
  # branchName: ${{ parameters.Branch }}
  # branchName: $(Build.SourceBranchName)
# variables:
#   branchName: ${{ trigger }}
# trigger:
# - main

pool:
  vmImage: windows-latest
resources:
  repositories:
    - repository: big_project
      type: github
      name: sridharraoallanki/big_project
      endpoint: sridharraoallanki
      ref: $(branchSource)
      
stages:
- stage:
  jobs:
  - job:
    steps:
      # - checkout: self

      - checkout: big_project
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)/'
          Contents: '**'
          TargetFolder: '$(System.DefaultWorkingDirectory)/dist'
      
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      - task: CmdLine@2
        displayName: 'List files'
        inputs:
          script: |
            for %%f in ( "$(Build.ArtifactStagingDirectory)\*" ) do @echo %%f
      # - task: PowerShell@2
      #   inputs:
      #     filePath: 'newps.ps1'
